# Generated by Django 3.0.3 on 2020-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_hands', '0002_category_donation_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default=1),
        ),
    ]
